pub mod auth;
pub mod control;
pub mod dashboard;
pub mod guilds;
pub mod health;
pub mod info;
pub mod oauth;
pub mod queue;
pub mod types;
pub mod analytics;

pub use auth::validate_auth;
pub use control::{play_pause, set_volume, stop_playback};
pub use dashboard::dashboard_redirect;
pub use guilds::get_guilds;
pub use health::{health_metrics, livez, readyz};
pub use info::{get_song_info, search_songs};
pub use oauth::oauth_callback;
pub use queue::{add_to_queue, clear_queue, get_queue, skip_track};
pub use analytics::{get_recent_tracks, get_guild_settings, get_cache_stats, update_guild_settings};
